version: '3'


services:
  db:
    image: postgres:13-alpine
    container_name: simple_bank_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: simple_bank
    ports:
      - "5001:5432"
    volumes:
      - mainDB:/var/lib/postgresql/data
    


volumes:
  mainDB: