
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/linuxbrew/.linuxbrew/share/cmake/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.1.91-060191-generic - x86_64
...
